version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command:
      - ./server
  app:
    build: ./app
    ports:
      - "3000:80"
    depends_on:
      - server
